### ISSUE TITLE
Add ssp emissions scenarios

### ISSUE THREAD

**Issue by eyvorchuk** [pacificclimate/pcic-react-components#14]
In order to have `ce-frontend` properly display the future emissions scenarios for CMIP6 data, the ssp scenarios (126, 245, and 585) should be added to the `EmissionsScenarioSelector` component.

**Comment by rod-glover** [comment]
[`EmissionsScenarioSelector`](https://github.com/pacificclimate/pcic-react-components/blob/master/src/lib/components/select/EmissionsScenarioSelector/EmissionsScenarioSelector.js) extracts the scenarios (a.k.a. experiments) from the metadata provided by the backend. In this case the metadata prop is `experiment`. 

If `experiment` continues to be the prop carrying the SSP scenarios, then the only thing that needs updating is how the SSP scenario codes are to be formatted for presentation; see [`formatPart`](https://github.com/pacificclimate/pcic-react-components/blob/14d818e05e4686f8e6d05a76fc2f6c4ee793f6d8/src/lib/components/select/EmissionsScenarioSelector/EmissionsScenarioSelector.js#L14).

If the SSP scenarios are specified in a different prop, then it will have to be added to [`representativeProps`](https://github.com/pacificclimate/pcic-react-components/blob/14d818e05e4686f8e6d05a76fc2f6c4ee793f6d8/src/lib/components/select/EmissionsScenarioSelector/EmissionsScenarioSelector.js#L32) and [`formatPart`](https://github.com/pacificclimate/pcic-react-components/blob/14d818e05e4686f8e6d05a76fc2f6c4ee793f6d8/src/lib/components/select/EmissionsScenarioSelector/EmissionsScenarioSelector.js#L14) modified accordingly. The (new) SSP prop will also have to be explicitly added in [CE's metadata pre-processing](https://github.com/pacificclimate/climate-explorer-frontend/blob/af9118e116bdfe7715416d4d84e87e83ac6e0496/src/data-services/ce-backend.js#L12-L40).
